import type { Metadata } from "next";
import localFont from "next/font/local";
import { Abel } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const abel = Abel({ subsets: ["latin"], 
  weight: ["400"],
  variable: "--font-abel",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${abel.className} ${geistSans.variable} ${geistMono.variable} antialiased  bg-gradient-to-b from-black to-[#26045c] transition-all hover:bg-gradient-to-br hover:from-[#32027e] hover:to-black`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}